module.exports.names = [
  "Dawn Gonzalez",
  "Courtney Mills",
  "Eddie Cain",
  "Chris Weaver",
  "Nina Reeves",
  "Karl Schwartz",
  "Melinda Griffin",
  "Katrina Duncan",
  "Dallas Francis",
  "Desiree Copeland",
  "Stanley Warren",
  "Catherine Hicks",
  "Alyssa Arnold",
  "Jordan Lloyd",
  "Grant Farmer",
  "Julia Mendoza",
  "Justin Scott",
  "Ramon Ortiz",
  "Vickie Harris",
  "Meredith Frank",
  "Josefina Stewart",
  "Leslie Hoffman",
  "Fernando Matthews",
  "Noah Lowe",
  "Conrad Jensen",
  "Lila Ramos",
  "Spencer Gardner",
  "Lynda Santiago",
  "Misty Flores",
  "Claude Roberts",
  "Gary Osborne",
  "Angel Snyder",
  "Terrell Kim",
  "Alicia Reed",
  "Elvira Lindsey",
  "Jeanne Briggs",
  "Jackie Strickland",
  "Pam Tran",
  "Larry Wallace",
  "Paul Sharp",
  "Paulette Meyer",
  "Victor Simon",
  "Brendan Hodges",
  "Rodney Lane",
  "Geraldine Robinson",
  "Essie Rodriguez",
  "Candice Craig",
  "Barbara Estrada",
  "Alfred Jacobs",
  "Miranda Kennedy",
  "Sidney Lyons",
  "Ellen Tucker",
  "Ebony Barker",
  "Cedric Carlson",
  "Rochelle Gibson",
  "Andrea Malone",
  "Troy Grant",
  "Kirk Richards",
  "Perry Cohen",
  "Randolph Alexander",
  "Dan Barnett",
  "Miguel Love",
  "Floyd Holland",
  "Eugene Alvarado",
  "Christie Rivera",
  "Delores Bailey",
  "Lora Wise",
  "Marlon Hansen",
  "Janis Hardy",
  "Lowell Thomas",
  "Rita Hunter",
  "Charles Steele",
  "Salvatore Garrett",
  "Jeannette Banks",
  "John Rhodes",
  "Johnnie Ryan",
  "Kara Murphy",
  "Lindsay Little",
  "Taylor Leonard",
  "Tasha Hamilton",
  "Shelly Lynch",
  "Natasha Nash",
  "Inez Logan",
  "Dora Fox",
  "Salvador Moore",
  "Sheila Caldwell",
  "Jon Bryan",
  "Pauline Fisher",
  "Jackie Wolfe",
  "Leon Erickson",
  "Daisy French",
  "Delia Riley",
  "Cornelius Jackson",
  "Cecilia Gomez",
  "Darlene West",
  "Phillip Curtis",
  "Gordon Baker",
  "Armando George",
  "Audrey Moreno",
  "Gerard Rowe",
];

module.exports.abouts = [
  "Hey guys! I'm Ammar, I'm a second year at UBC studying biomedical engineering. I'm somewhat comfortable with java and python. I've been to one hackathon before, so I'm really just open to learn and delve into different areas of development. If you need a team member or  something please feel free to shoot me a message so we can get to know each other",
  "Hi everyone! I'm Warren. I'm a 4th year mathematics student at the St. George Campus. I am comfortable with Python,  R, SQL, a bit of Java and HTML as well as with machine learning tools such as tensorflow, pandas and sklearn. I'm excited to learn something new from this hackathon and have fun. If you need a teammate, please feel free to send me a message.",
  "hey y'all, i'm currently a sophomore at queen's university studying CS.  Over the last year I've gained skills in full stack development, mainly comfortable with react, node, django and flask. Here's my portfolio if interested in my past projects https://ronan.tech/  Feel free to DM me if interested in forming a team.",
  "Hi everyone my name is Elad and I'm a second year at UofT St. George. I'm in a team of 3 and we're currently looking for one more. If you have experience with Swift/iOS Development/Objective C/Database backend and are interested in making an iOS application then feel free to DM me to join the team.",
  "Hey all, I'm a math major at Athabasca University. I'm experienced in ML (ranked 1100th on Kaggle, Google's data science platform), and have 5 hackathon wins, including one at UBC. I'm looking for someone who is dedicated and very experienced in web development , preferably flask/django to join my team of 2 and possibly fight for a win.",
  "Hi all, final year EE here with decent amount of hackathon experience and previous wins including previous uoft hacks . Experienced with ml, web apps, cloud, and android dev. Im more of a backend but can also do some front end. Looking to work on something cool and have fun! Interested in working on a web or mobile app but I’m open to anything cool.",
  "Hey everyone! My name is Munazza, I am a third-year Software Engineering student at the University of Ontario Institute of Technology. This is my second hackathon, the last hackathon I participated in was SheHacks and the project was a 2nd place winner. I have experience with Java, C++, python, Swift, HTML and CSS. I also have basic experience with Figma (UX design) as well as Adobe suite. I am also up for learning any kind of other software and languages! :slight_smile:",
  "Hi guys, my name is Anindya. I am a 4th year CS and Cognitive Science student at U of T. During the short period of this hackathon, I would like to complete a project that tackles a real life issue in a creative way. I have previous experience in Software Development, Machine Learning/AI and Neuroscience research. Feel free to contact me if you are interested in teaming up!",
  "Hi everyone! My name is Milos and I am a 4th year design student at Sheridan College studying Interaction Design. This is my first hackathon and I am super excited to meet new creative people, collaborate, have fun and create/design a cool project that can be applied as a solution in real world scenarios. I am a multidisciplinary designer, I love anything with visual design, UI/UX design and research and I have experience with front-end development in HTML/CSS. I’m looking forward to being part of a team so feel free to contact me if you’d like to team up!",
  "Hey everyone! @Rachel Kim and I are first year CS students at UofT. Our experiences include: Python, pandas and scikit-learn libraries, R, Java and C++. We are new to hackathons, but we are excited to learn more about them! If you are interested in teaming up message either of us. Thanks!",
  "I'm a first year CS major at UWaterloo, This is my second hackathon. My first one was Stanford's Treehacks. I'm dedicated and experienced in web development with Python Flask, and React.JS, and would love to work on the frontend. I have access to Open AI's GPT-3, and would love to implement it into a project with ML/AI. I'm in EST (Toronto time), but I'm open to any ideas or to join an existing team. Feel free to hit me up if you're interested! :blush:.",
  "Hey everyone, my name is Ari and I'm a second year at Ritsumeikan Uni  :flag_jp: .  I mainly work with Swift and Python but I've done a lot of projects as a full-stack as well. (Web designing, databases NoSQL & SQL, API developments, Server Config ). I also know a bit about ML and for designing I mainly use Figma.  I've also recently started to work on some projects with IPFS and blockchains. Feel free to message me if you're looking for a member.:grinning: With using this app you can track your body symptoms such as body temperature (celsius), cough, sore throat and shortness of breath.",
  "Hey everyone, I'm Kevin. I'm a third year computer engineering student at UWaterloo (Well, entering third year, I'm on co-op rn). This is my second hackathon. I mainly use C++, Python and SQL but I do have some experience in Java and have been dabbling in React and Flutter recently. I'm open to working on anything so just shoot me a DM if you need a member.",
  "Hi, I'm Sarah, and I'm in my last year of high school. This is my first hackathon, and I have a little bit of experience in Java and C++. Please message me if you're open to working together!",
  "Hi, I'm Ian, grade 12. First hackathon, experience in Java, C++ and PHP. DM if you're looking for +2 members :)",
  "Hi everyone! My name is David. I'm a second year CS and Stats student at UofT St. George campus. This is my first hackathon so I am new to this. I am familiar with Python including NumPy and PyTorch, and also Java. I'm open to working on any project! Please message me if you are looking for a member!",
  "Hi, I'm Brennan, first year CS at Calpoly. First hackathon, and hoping to use this as an experience to learn more about coding",
  "Hey everyone! I’m a CS student at UWO (currently on internship, going into 4th year) with an interest in  distributed systems. I have experience developing enterprise applications in ReactJS and Java Spring and have some ci/cd experience. I'm willing to use Java/nodejs, but I'd prefer to flesh out my python experience (building sites with flask, CLI tools with click, discord bots, and web scrapping with bs4.) I can work on the backend or frontend or help out with anything environment related (got docker exp) or deployment related (dabbled with aws eb). I’ve been to 2 hackathons prior, would like a semi-experienced team (knows git). DMs are open ^^",
  "hi everyone, my friend Rachel Pun and i are currently looking for 2 more teammates to join our team! im christine and im studying electrical engineering at waterloo. i have many prior software dev internship experiences, and am skilled at fontend mobile/web dev (react/react native, sql, html/css, javascript, python, c++, java..etc)",
  "connect with me on linkedin: https://www.linkedin.com/in/christine-trac/my partner rachel is studying design at york/sheridan. she is amazing at using figma, adobe..etc and making mockups/designs for mobile/web apps!",
  "her linkedin is: https://www.linkedin.com/in/rac-help/ we've done 2 previous hackathons together and have won a category before. we're looking for backend devs that are familiar with servers (firebase, aws..etc) or databases and/or machine learning/ai that can create a backend for our frontend! or frontend devs experienced in react native! please dm either of us if you're interested in joining our team :)",
  "heres my devpost to see our prev. Christine Trac specializes in Java, JavaScript, React, React Native, Sql, CSS, HTML5, Python, C++, Groovy, Grails, Node.js, TypeScript, Matlab, Figma, and Liqud. Follow Christine Trac on Devpost!",
  "Hello, I'm Ashley, grade 11 student. This will be my first hackathon. I have some experience in Python and a bit in Lua. I'm looking forward to learning new things! Message me to form a team :slight_smile:",
  "Hey guys, Im Lamia. I am a 4th year (+ PEY) industrial engineering student at UofT and this is my 2nd hackathon. My background is in UX/UI Design and Research. I also have experience with Python, Java, R and HTML/CSS. I am open to any ideas. Feel free to message me if you're looking for a team member :slight_smile:",
  "Hey everyone! I'm Dana. I'm a first year CS student at UofTsg. This is my first hackathon so I'm not too sure what to expect. I'm familiar with Python, C#, R and  SQL. Feel free to contact if you'd like to team up!",
  "Hi everyone, I'm a third year computer science student from Ontario Tech. I have attended two hackathons before and I'm familiar with the MERN stack for web dev and python for data science and ML. Please message me if you would like to form a team",
  "Hi im a 2nd year CS student at Ryerson. I have a networking and IT security background. Along with some solid programming foundation in Python. This is my first hackathon. Please message me if you want to form a team.",
  "Hi everyone, I'm in Mech eng completing my final year at McGill university. This will be my first hackathon, and I am down to work on anything. I am familiar mainly with Python, Matlab, and VBA. Message me if you want to form a team!",
  "This is Arsalaan, A high school senior. I am a proficient front-end web developer knowing (HTML/CSS/JS/REACT) deeply, Im also a solid video editor and a workflow planner. I am currently interning as a Junior Cybersecurity specialist. I am always ready to learn and do hardwork. This would be my 3rd major hackathon. I am currently brainstorming ideas. I am looking to team with people. You can see my profile here:",
  "Hey everyone, I'm a 2nd year cs student from waterloo. Most of my programming experience is in web development using languages such as react html css and js. Im also proficient in python.  This is my 3rd major hackathon and I would love to work with any of yall to make something fun. Tbh my goal isn't to win the hackathon I just wanna learn some stuff and make some friends along the way but if we wanna try and win im down for that too!",
  "Hey everyone,  I am a second-year CS student at UTSG. This is my first hackathon and I am familiar with python and Java. I am open to any project, so if you need a team member, feel free to message me.",
  "Hi everyone, I'm a second year computer science specialist at UTSG, familiar with python and java, know some C and learned a little bit of javascript and html. I have plenty of project management experiences (from being the leader of a course coding project and of a club at UofT). It's my first time attending a hackathon and I'm very looking forward to learning new things and having fun hacking with my team! :slight_smile: Feel free to message me if you need a team member! [UPDATE: got into a team and team full]",
  "Hi guys! I’m Kevin and I’m in second year mechatronics engineering at McMaster. I am familiar with Java and C and I know some python and C++. This is my first hackathon and I’m looking forward to learning new things and meeting new people. Message me if you need another team member!",
  "Hi again (not that anyone is expected to remember my first post). We are an Android team of three and looking for a fourth member to join us! If you have experience with Android development with Java and Android Studio, please don't hesitate to reach out to me. I have worked on several Android projects at hackathons in the last month and looking to make a cool app this weekend!",
  "Hey guys, I am Samson, 3rd year IT at yorkU. I have intern experience in computer vision with gesture detection, frond-end and data analysis. I am looking for people who are interested in working on web/ML/data related part, so DM me if any of you guys are interested in teaming up and learn together in this hack!!",
  "Hey all, I'm a 4th year at UTSC, and so is my friend @Hemant Bhanot. We've both done many internships in the past. We've participated in many hackathons and recently won best use of GCP at Hack the North 2020++, and we placed top 10 at another hackathon!",
  "We're looking for two motivated people to join our team, preferably designers/front-end devs! mate and I are both 3rd year UofT CS students. I have web and android development experience. Please DM if you are interested in joining our team!",
];

module.exports.countrieRegions = [
  { name: "Afghanistan", code: "AF" },
  { name: "Åland Islands", code: "AX" },
  { name: "Albania", code: "AL" },
  { name: "Algeria", code: "DZ" },
  { name: "American Samoa", code: "AS" },
  { name: "AndorrA", code: "AD" },
  { name: "Angola", code: "AO" },
  { name: "Anguilla", code: "AI" },
  { name: "Antarctica", code: "AQ" },
  { name: "Antigua and Barbuda", code: "AG" },
  { name: "Argentina", code: "AR" },
  { name: "Armenia", code: "AM" },
  { name: "Aruba", code: "AW" },
  { name: "Australia", code: "AU" },
  { name: "Austria", code: "AT" },
  { name: "Azerbaijan", code: "AZ" },
  { name: "Bahamas", code: "BS" },
  { name: "Bahrain", code: "BH" },
  { name: "Bangladesh", code: "BD" },
  { name: "Barbados", code: "BB" },
  { name: "Belarus", code: "BY" },
  { name: "Belgium", code: "BE" },
  { name: "Belize", code: "BZ" },
  { name: "Benin", code: "BJ" },
  { name: "Bermuda", code: "BM" },
  { name: "Bhutan", code: "BT" },
  { name: "Bolivia", code: "BO" },
  { name: "Bosnia and Herzegovina", code: "BA" },
  { name: "Botswana", code: "BW" },
  { name: "Bouvet Island", code: "BV" },
  { name: "Brazil", code: "BR" },
  { name: "British Indian Ocean Territory", code: "IO" },
  { name: "Brunei Darussalam", code: "BN" },
  { name: "Bulgaria", code: "BG" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Burundi", code: "BI" },
  { name: "Cambodia", code: "KH" },
  { name: "Cameroon", code: "CM" },
  { name: "Canada", code: "CA" },
  { name: "Cape Verde", code: "CV" },
  { name: "Cayman Islands", code: "KY" },
  { name: "Central African Republic", code: "CF" },
  { name: "Chad", code: "TD" },
  { name: "Chile", code: "CL" },
  { name: "China", code: "CN" },
  { name: "Christmas Island", code: "CX" },
  { name: "Cocos (Keeling) Islands", code: "CC" },
  { name: "Colombia", code: "CO" },
  { name: "Comoros", code: "KM" },
  { name: "Congo", code: "CG" },
  { name: "Congo, The Democratic Republic of the", code: "CD" },
  { name: "Cook Islands", code: "CK" },
  { name: "Costa Rica", code: "CR" },
  { name: "Cote D'Ivoire", code: "CI" },
  { name: "Croatia", code: "HR" },
  { name: "Cuba", code: "CU" },
  { name: "Cyprus", code: "CY" },
  { name: "Czech Republic", code: "CZ" },
  { name: "Denmark", code: "DK" },
  { name: "Djibouti", code: "DJ" },
  { name: "Dominica", code: "DM" },
  { name: "Dominican Republic", code: "DO" },
  { name: "Ecuador", code: "EC" },
  { name: "Egypt", code: "EG" },
  { name: "El Salvador", code: "SV" },
  { name: "Equatorial Guinea", code: "GQ" },
  { name: "Eritrea", code: "ER" },
  { name: "Estonia", code: "EE" },
  { name: "Ethiopia", code: "ET" },
  { name: "Falkland Islands (Malvinas)", code: "FK" },
  { name: "Faroe Islands", code: "FO" },
  { name: "Fiji", code: "FJ" },
  { name: "Finland", code: "FI" },
  { name: "France", code: "FR" },
  { name: "French Guiana", code: "GF" },
  { name: "French Polynesia", code: "PF" },
  { name: "French Southern Territories", code: "TF" },
  { name: "Gabon", code: "GA" },
  { name: "Gambia", code: "GM" },
  { name: "Georgia", code: "GE" },
  { name: "Germany", code: "DE" },
  { name: "Ghana", code: "GH" },
  { name: "Gibraltar", code: "GI" },
  { name: "Greece", code: "GR" },
  { name: "Greenland", code: "GL" },
  { name: "Grenada", code: "GD" },
  { name: "Guadeloupe", code: "GP" },
  { name: "Guam", code: "GU" },
  { name: "Guatemala", code: "GT" },
  { name: "Guernsey", code: "GG" },
  { name: "Guinea", code: "GN" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Guyana", code: "GY" },
  { name: "Haiti", code: "HT" },
  { name: "Heard Island and Mcdonald Islands", code: "HM" },
  { name: "Holy See (Vatican City State)", code: "VA" },
  { name: "Honduras", code: "HN" },
  { name: "Hungary", code: "HU" },
  { name: "Iceland", code: "IS" },
  { name: "India", code: "IN" },
  { name: "Indonesia", code: "ID" },
  { name: "Iran, Islamic Republic Of", code: "IR" },
  { name: "Iraq", code: "IQ" },
  { name: "Ireland", code: "IE" },
  { name: "Isle of Man", code: "IM" },
  { name: "Israel", code: "IL" },
  { name: "Italy", code: "IT" },
  { name: "Jamaica", code: "JM" },
  { name: "Japan", code: "JP" },
  { name: "Jersey", code: "JE" },
  { name: "Jordan", code: "JO" },
  { name: "Kazakhstan", code: "KZ" },
  { name: "Kenya", code: "KE" },
  { name: "Kiribati", code: "KI" },
  { name: "Korea, Democratic People'S Republic of", code: "KP" },
  { name: "Korea, Republic of", code: "KR" },
  { name: "Kuwait", code: "KW" },
  { name: "Kyrgyzstan", code: "KG" },
  { name: "Lao People'S Democratic Republic", code: "LA" },
  { name: "Latvia", code: "LV" },
  { name: "Lebanon", code: "LB" },
  { name: "Lesotho", code: "LS" },
  { name: "Liberia", code: "LR" },
  { name: "Libyan Arab Jamahiriya", code: "LY" },
  { name: "Liechtenstein", code: "LI" },
  { name: "Lithuania", code: "LT" },
  { name: "Luxembourg", code: "LU" },
  { name: "Macao", code: "MO" },
  { name: "Macedonia, The Former Yugoslav Republic of", code: "MK" },
  { name: "Madagascar", code: "MG" },
  { name: "Malawi", code: "MW" },
  { name: "Malaysia", code: "MY" },
  { name: "Maldives", code: "MV" },
  { name: "Mali", code: "ML" },
  { name: "Malta", code: "MT" },
  { name: "Marshall Islands", code: "MH" },
  { name: "Martinique", code: "MQ" },
  { name: "Mauritania", code: "MR" },
  { name: "Mauritius", code: "MU" },
  { name: "Mayotte", code: "YT" },
  { name: "Mexico", code: "MX" },
  { name: "Micronesia, Federated States of", code: "FM" },
  { name: "Moldova, Republic of", code: "MD" },
  { name: "Monaco", code: "MC" },
  { name: "Mongolia", code: "MN" },
  { name: "Montserrat", code: "MS" },
  { name: "Morocco", code: "MA" },
  { name: "Mozambique", code: "MZ" },
  { name: "Myanmar", code: "MM" },
  { name: "Namibia", code: "NA" },
  { name: "Nauru", code: "NR" },
  { name: "Nepal", code: "NP" },
  { name: "Netherlands", code: "NL" },
  { name: "Netherlands Antilles", code: "AN" },
  { name: "New Caledonia", code: "NC" },
  { name: "New Zealand", code: "NZ" },
  { name: "Nicaragua", code: "NI" },
  { name: "Niger", code: "NE" },
  { name: "Nigeria", code: "NG" },
  { name: "Niue", code: "NU" },
  { name: "Norfolk Island", code: "NF" },
  { name: "Northern Mariana Islands", code: "MP" },
  { name: "Norway", code: "NO" },
  { name: "Oman", code: "OM" },
  { name: "Pakistan", code: "PK" },
  { name: "Palau", code: "PW" },
  { name: "Palestinian Territory, Occupied", code: "PS" },
  { name: "Panama", code: "PA" },
  { name: "Papua New Guinea", code: "PG" },
  { name: "Paraguay", code: "PY" },
  { name: "Peru", code: "PE" },
  { name: "Philippines", code: "PH" },
  { name: "Pitcairn", code: "PN" },
  { name: "Poland", code: "PL" },
  { name: "Portugal", code: "PT" },
  { name: "Puerto Rico", code: "PR" },
  { name: "Qatar", code: "QA" },
  { name: "Reunion", code: "RE" },
  { name: "Romania", code: "RO" },
  { name: "Russian Federation", code: "RU" },
  { name: "RWANDA", code: "RW" },
  { name: "Saint Helena", code: "SH" },
  { name: "Saint Kitts and Nevis", code: "KN" },
  { name: "Saint Lucia", code: "LC" },
  { name: "Saint Pierre and Miquelon", code: "PM" },
  { name: "Saint Vincent and the Grenadines", code: "VC" },
  { name: "Samoa", code: "WS" },
  { name: "San Marino", code: "SM" },
  { name: "Sao Tome and Principe", code: "ST" },
  { name: "Saudi Arabia", code: "SA" },
  { name: "Senegal", code: "SN" },
  { name: "Serbia and Montenegro", code: "CS" },
  { name: "Seychelles", code: "SC" },
  { name: "Sierra Leone", code: "SL" },
  { name: "Singapore", code: "SG" },
  { name: "Slovakia", code: "SK" },
  { name: "Slovenia", code: "SI" },
  { name: "Solomon Islands", code: "SB" },
  { name: "Somalia", code: "SO" },
  { name: "South Africa", code: "ZA" },
  { name: "South Georgia and the South Sandwich Islands", code: "GS" },
  { name: "Spain", code: "ES" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Sudan", code: "SD" },
  { name: "Suriname", code: "SR" },
  { name: "Svalbard and Jan Mayen", code: "SJ" },
  { name: "Swaziland", code: "SZ" },
  { name: "Sweden", code: "SE" },
  { name: "Switzerland", code: "CH" },
  { name: "Syrian Arab Republic", code: "SY" },
  { name: "Tajikistan", code: "TJ" },
  { name: "Tanzania, United Republic of", code: "TZ" },
  { name: "Thailand", code: "TH" },
  { name: "Timor-Leste", code: "TL" },
  { name: "Togo", code: "TG" },
  { name: "Tokelau", code: "TK" },
  { name: "Tonga", code: "TO" },
  { name: "Trinidad and Tobago", code: "TT" },
  { name: "Tunisia", code: "TN" },
  { name: "Turkey", code: "TR" },
  { name: "Turkmenistan", code: "TM" },
  { name: "Turks and Caicos Islands", code: "TC" },
  { name: "Tuvalu", code: "TV" },
  { name: "Uganda", code: "UG" },
  { name: "Ukraine", code: "UA" },
  { name: "United Arab Emirates", code: "AE" },
  { name: "United Kingdom", code: "GB" },
  { name: "United States", code: "US" },
];

module.exports.cities = [
    ["FUGEREVILLE", "QC"],
    ["FULDA", "SK"],
    ["FULFORD", "QC"],
    ["FULLARTON", "ON"],
    ["FUNDY NATIONAL PARK", "NB"],
    ["FURDALE", "SK"],
    ["FURRY CREEK", "BC"],
    ["GABARUS LAKE", "NS"],
    ["GABARUS", "NS"],
    ["GABRIOLA", "BC"],
    ["GADS HILL STATION", "ON"],
    ["GADSBY", "AB"],
    ["GAGETOWN", "NB"],
    ["GAINFORD", "AB"],
    ["GAINSBOROUGH", "SK"],
    ["GALAHAD", "AB"],
    ["GALIANO", "BC"],
    ["GALLAGHER RIDGE", "NB"],
    ["GALLANTS", "NL"],
    ["GALLICHAN", "QC"],
    ["GALLIVAN", "SK"],
    ["GALLIX", "QC"],
    ["GALLOWAY", "BC"],
    ["GALLOWAY", "NB"],
    ["GAMBO SOUTH", "NL"],
    ["GAMBO", "NL"],
    ["GAMETI", "NT"],
    ["GANANOQUE", "ON"],
    ["GANDER BAY SOUTH", "NL"],
    ["GANDER BAY", "NL"],
    ["GANDER", "NL"],
    ["GANG RANCH", "BC"],
    ["GARDEN BAY", "BC"],
    ["GARDEN COVE PB", "NL"],
    ["GARDEN RIVER", "AB"],
    ["GARDEN RIVER", "ON"],
    ["GARDEN VILLAGE", "ON"],
    ["GARDENTON", "MB"],
    ["GARDINER MINES", "NS"],
    ["GARDINER POINT", "NB"],
    ["GARDNER CREEK", "NB"],
    ["GARIBALDI HIGHLANDS", "BC"],
    ["GARLAND", "MB"],
    ["GARNETT SETTLEMENT", "NB"],
    ["GARNISH", "NL"],
    ["GARRICK", "SK"],
    ["GARSON", "MB"],
    ["GARSON", "ON"],
    ["GASCONS", "QC"],
    ["GASPE", "QC"],
    ["GASPEREAU FORKS", "NB"],
    ["GATINEAU", "ON"],
    ["GATINEAU", "QC"],
    ["GAULTOIS", "NL"],
    ["GAUVREAU", "NB"],
    ["GAYS RIVER", "NS"],
    ["GEARY", "NB"],
    ["GEM", "AB"],
    ["GENELLE", "BC"],
    ["GEORGES RIVER", "NS"],
    ["GEORGETOWN", "ON"],
    ["GEORGETOWN", "PE"],
    ["GEORGEVILLE", "QC"],
    ["GERALD", "SK"],
    ["GERALDTON", "ON"],
    ["GERMANSEN LANDING", "BC"],
    ["GERMANTOWN", "NB"],
    ["GETHSEMANI", "QC"],
    ["GIANTS GLEN", "NB"],
    ["GIBBONS", "AB"],
    ["GIBSONS", "BC"],
    ["GIFT LAKE", "AB"],
    ["GILBERT PLAINS", "MB"],
    ["GILFORD", "ON"],
    ["GILLAM", "MB"],
    ["GILLIES BAY", "BC"],
    ["GILLIS LAKE", "NS"],
    ["GILLIS POINT", "NS"],
    ["GILMOUR", "ON"],
    ["GIMLI", "MB"],
    ["GINEW", "MB"],
    ["GIRARDVILLE", "QC"],
    ["GIROUX", "MB"],
    ["GIROUXVILLE", "AB"],
    ["GITWINKSIHLKW", "BC"],
    ["GJOA HAVEN", "NU"],
    ["GLACE BAY", "NS"],
    ["GLADESIDE", "NB"],
    ["GLADMAR", "SK"],
    ["GLADSTONE", "MB"],
    ["GLADWYN", "NB"],
    ["GLASLYN", "SK"],
    ["GLASNEVIN", "SK"],
    ["GLASSVILLE", "NB"],
    ["GLEICHEN", "AB"],
    ["GLEN EWEN", "SK"],
    ["GLEN HAVEN", "NS"],
    ["GLEN HURON", "ON"],
    ["GLEN MARGARET", "NS"],
    ["GLEN MORRIS", "ON"],
    ["GLEN ROBERTSON", "ON"],
    ["GLENAVON", "SK"],
    ["GLENBAIN", "SK"],
    ["GLENBORO", "MB"],
    ["GLENBURNIE", "ON"],
    ["GLENBUSH", "SK"],
    ["GLENCAIRN", "ON"],
    ["GLENCOE", "NB"],
    ["GLENCOE", "ON"],
    ["GLENDON", "AB"],
    ["GLENELLA", "MB"],
    ["GLENEVIS", "AB"],
    ["GLENLEA", "MB"],
    ["GLENLEVIT", "NB"],
    ["GLENORA", "MB"],
    ["GLENSIDE", "SK"],
    ["GLENTWORTH", "SK"],
    ["GLENVALE", "NB"],
    ["GLENWOOD KINGS CO", "NB"],
    ["GLENWOOD", "AB"],
    ["GLENWOOD", "NB"],
    ["GLENWOOD", "NL"],
    ["GLENWOOD", "NS"],
    ["GLENWOOD.", "NB"],
    ["GLIDDEN", "SK"],
    ["GLOUCESTER JUNCTION", "NB"],
    ["GLOUCESTER", "ON"],
    ["GLOVERTOWN SOUTH", "NL"],
    ["GLOVERTOWN", "NL"],
    ["GODBOUT", "QC"],
    ["GODERICH", "ON"],
    ["GODFREY", "ON"],
    ["GODMANCHESTER", "QC"],
    ["GODS LAKE NARROWS", "MB"],
    ["GODS RIVER", "MB"],
    ["GOFFS", "NS"],
    ["GOGAMA", "ON"],
    ["GOLD BRIDGE", "BC"],
    ["GOLD RIVER", "BC"],
    ["GOLDBORO", "NS"],
    ["GOLDEN LAKE", "ON"],
    ["GOLDEN PRAIRIE", "SK"],
    ["GOLDEN VALLEY", "ON"],
    ["GOLDEN", "BC"],
    ["GOOD CORNER", "NB"],
    ["GOOD HOPE LAKE", "BC"],
    ["GOODERHAM", "ON"],
    ["GOODEVE", "SK"],
    ["GOODFARE", "AB"],
    ["GOODFISH LAKE", "AB"],
    ["GOODLANDS", "MB"],
    ["GOODLOW", "BC"],
    ["GOODRIDGE", "AB"],
    ["GOODSOIL", "SK"],
    ["GOODWATER", "SK"],
    ["GOODWIN MILL", "NB"],
    ["GOODWOOD", "NS"],
    ["GOODWOOD", "ON"],
    ["GOOSEBERRY COVE", "NL"],
    ["GORDONDALE", "AB"],
    ["GORDONSVILLE", "NB"],
    ["GORE BAY", "ON"],
    ["GORE", "QC"],
    ["GORES LANDING", "ON"],
    ["GORMLEY", "ON"],
    ["GORRIE", "ON"],
    ["GOSHEN", "NS"],
    ["GOULAIS RIVER", "ON"],
    ["GOULDS", "NL"],
    ["GOULDTOWN", "SK"],
    ["GOVAN", "SK"],
    ["GOWANSTOWN", "ON"],
    ["GOWGANDA", "ON"],
    ["GRACEFIELD", "QC"],
    ["GRAFTON", "NB"],
    ["GRAFTON", "ON"],
    ["GRAHAM", "ON"],
    ["GRAHAMDALE", "MB"],
    ["GRANBY", "QC"],
    ["GRAND BANK", "NL"],
    ["GRAND BAY EAST", "NL"],
    ["GRAND BAY-WESTFIELD", "NB"],
    ["GRAND BEACH", "NL"],
    ["GRAND BEND", "ON"],
    ["GRAND BRUIT", "NL"],
    ["GRAND ETANG", "NS"],
    ["GRAND FALLS", "NB"],
    ["GRAND FALLS-WINDSOR", "NL"],
    ["GRAND FORKS", "BC"],
    ["GRAND LAKE ROAD", "NB"],
    ["GRAND LAKE ROAD", "NS"],
    ["GRAND LAKE", "NS"],
    ["GRAND LE PIERRE", "NL"],
    ["GRAND MANAN", "NB"],
    ["GRAND MARAIS", "MB"],
    ["GRAND MIRA NORTH", "NS"],
    ["GRAND MIRA SOUTH", "NS"],
    ["GRAND NARROWS", "NS"],
    ["GRAND PRE", "NS"],
    ["GRAND RAPIDS", "MB"],
    ["GRAND RIVER", "NS"],
    ["GRAND VALLEY", "ON"],
    ["GRAND-BARACHOIS", "NB"],
    ["GRAND-MERE", "QC"],
    ["GRAND-REMOUS", "QC"],
    ["GRAND-SAINT-ESPRIT", "QC"],
    ["GRAND-SAULT/GRAND FALLS", "NB"],
    ["GRANDE CACHE", "AB"],
    ["GRANDE POINTE", "MB"],
    ["GRANDE POINTE", "ON"],
    ["GRANDE PRAIRIE", "AB"],
    ["GRANDE-ANSE", "NB"],
    ["GRANDE-DIGUE", "NB"],
    ["GRANDE-ENTREE", "QC"],
    ["GRANDE-RIVIERE", "QC"],
    ["GRANDE-RIVIERE-OUEST", "QC"],
    ["GRANDE-VALLEE", "QC"],
    ["GRANDES-BERGERONNES", "QC"],
    ["GRANDES-PILES", "QC"],
    ["GRANDORA", "SK"],
    ["GRANDVIEW", "MB"],
    ["GRANISLE", "BC"],
    ["GRANTON", "ON"],
    ["GRANUM", "AB"],
    ["GRANVILLE FERRY", "NS"],
    ["GRASMERE", "BC"],
    ["GRASS COVE", "NS"],
    ["GRASSIE", "ON"],
    ["GRASSLAND", "AB"],
    ["GRASSWOOD", "SK"],
    ["GRASSY LAKE", "AB"],
    ["GRASSY NARROWS", "ON"],
    ["GRATES COVE", "NL"],
    ["GRAVEL HILL", "NB"],
    ["GRAVELBOURG", "SK"],
    ["GRAVENHURST", "ON"],
    ["GRAY CREEK", "BC"],
    ["GRAY RAPIDS", "NB"],
    ["GRAY", "SK"],
    ["GRAYSON", "SK"],
    ["GRAYSVILLE", "MB"],
    ["GREAT FALLS", "MB"],
    ["GREAT VILLAGE", "NS"],
    ["GREATER LAKEBURN", "NB"],
    ["GREELY", "ON"],
    ["GREEN BAY", "NS"],
    ["GREEN CREEK", "NS"],
    ["GREEN GABLES", "PE"],
    ["GREEN HILL", "NB"],
    ["GREEN ISLAND BROOK", "NL"],
    ["GREEN ISLAND COVE", "NL"],
    ["GREEN LAKE", "SK"],
    ["GREEN MOUNTAIN", "NB"],
    ["GREEN OAKS", "NS"],
    ["GREEN RIDGE", "MB"],
    ["GREEN ROAD", "NB"],
    ["GREEN VALLEY", "ON"],
    ["GREENBANK", "ON"],
    ["GREENFIELD PARK", "QC"],
    ["GREENFIELD", "NB"],
    ["GREENFIELD", "NS"],
    ["GREENFIELD.", "NS"],
    ["GREENHILL LAKE", "NB"],
    ["GREENS HARBOUR", "NL"],
    ["GREENSPOND", "NL"],
    ["GREENVILLE", "BC"],
    ["GREENWOOD", "BC"],
    ["GREENWOOD", "NS"],
    ["GREENWOOD", "ON"],
    ["GREGG SETTLEMENT", "NB"],
    ["GRENFELL", "SK"],
    ["GRENVILLE", "QC"],
    ["GRENVILLE-SUR-LA-ROUGE", "QC"],
    ["GRETNA", "MB"],
    ["GREY RIVER", "NL"],
    ["GRIFFIN", "SK"],
    ["GRIFFITH", "ON"],
    ["GRIMMS SETTLEMENT", "NS"],
    ["GRIMSBY", "ON"],
    ["GRIMSHAW", "AB"],
    ["GRINDROD", "BC"],
    ["GRISE FIORD", "NU"],
    ["GRISWOLD", "MB"],
    ["GRONDINES", "QC"],
    ["GRONLID", "SK"],
    ["GROS-MORNE", "QC"],
    ["GROSSE ISLE", "MB"],
    ["GROSSE-ILE", "QC"],
    ["GROSSES-ROCHES", "QC"],
    ["GROUARD", "AB"],
    ["GROUNDBIRCH", "BC"],
    ["GROVE HILL", "NB"],
    ["GROVEDALE", "AB"],
    ["GROVES POINT", "NS"],
    ["GRUNTHAL", "MB"],
    ["GUELPH", "ON"],
    ["GUERIN", "QC"],
    ["GUERNSEY", "SK"],
    ["GULL BAY", "ON"],
    ["GULL LAKE", "SK"],
    ["GUNDY", "AB"],
    ["GUNN", "AB"],
    ["GUNTON", "MB"],
    ["GUY", "AB"],
    ["GUYENNE", "QC"],
    ["GUYSBOROUGH", "NS"],
    ["GWYNNE", "AB"],
    ["GYPSUMVILLE", "MB"],
    ["HACHEYVILLE", "NB"],
    ["HACKETTS COVE", "NS"],
    ["HADASHVILLE", "MB"],
    ["HAFFORD", "SK"],
    ["HAGAR", "ON"],
    ["HAGEN", "SK"],
    ["HAGENSBORG", "BC"],
    ["HAGERSVILLE", "ON"],
    ["HAGUE", "SK"],
    ["HAILEYBURY", "ON"],
    ["HAINES JUNCTION", "YT"],
    ["HAIRY HILL", "AB"],
    ["HAISLA", "BC"],
    ["HALBRITE", "SK"],
    ["HALBSTADT", "MB"],
    ["HALCOMB", "NB"],
    ["HALEY STATION", "ON"],
    ["HALFMOON BAY", "AB"],
    ["HALFMOON BAY", "BC"],
    ["HALIBURTON", "ON"],
    ["HALIBUT BAY", "NS"],
    ["HALIFAX", "NS"],
    ["HALKIRK", "AB"],
    ["HALL BEACH", "NU"],
    ["HALLEBOURG", "ON"],
    ["HAM-NORD", "QC"],
    ["HAMILTON", "ON"],
    ["HAMIOTA", "MB"],
    ["HAMMOND", "ON"],
    ["HAMMONDS PLAINS", "NS"],
    ["HAMMONDVALE", "NB"],
    ["HAMPDEN", "NL"],
    ["HAMPSTEAD", "NB"],
    ["HAMPSTEAD", "QC"],
    ["HAMPTON", "NB"],
    ["HAMPTON", "NS"],
    ["HAMPTON", "ON"],
    ["HAMTOWN CORNER", "NB"],
    ["HANCEVILLE", "BC"],
    ["HANDEL", "SK"],
    ["HANEYTOWN", "NB"],
    ["HANFORD BROOK", "NB"],
    ["HANLEY", "SK"],
    ["HANMER", "ON"],
    ["HANNA", "AB"],
    ["HANNON", "ON"],
    ["HANOVER", "ON"],
    ["HANTS HARBOUR", "NL"],
    ["HANTSPORT", "NS"],
    ["HANWELL", "NB"],
    ["HAPPY VALLEY-GOOSE BAY", "NL"],
    ["HARBOUR BRETON", "NL"],
    ["HARBOUR GRACE SOUTH", "NL"],
    ["HARBOUR GRACE", "NL"],
    ["HARBOUR MAIN", "NL"],
    ["HARBOUR MILLE", "NL"],
    ["HARBOUR ROUND", "NL"],
    ["HARCOURT", "NB"],
    ["HARCOURT", "ON"],
    ["HARDING", "MB"],
    ["HARDISTY", "AB"],
    ["HARDWICKE", "NB"],
    ["HARDWOOD LANDS", "NS"],
    ["HARDWOOD RIDGE", "NB"],
    ["HARE BAY BB", "NL"],
    ["HAREWOOD", "NB"],
    ["HARGRAVE", "MB"],
    ["HARLEY", "ON"],
    ["HARMONY", "NS"],
    ["HARRIETSFIELD", "NS"],
    ["HARRIETSVILLE", "ON"],
    ["HARRINGTON HARBOUR", "QC"],
    ["HARRINGTON", "QC"],
    ["HARRIS", "SK"],
    ["HARRISON HOT SPRINGS", "BC"],
    ["HARRISON MILLS", "BC"],
    ["HARRISTON", "ON"],
    ["HARROGATE", "BC"],
    ["HARROW", "ON"],
    ["HARROWSMITH", "ON"],
    ["HARRYS HARBOUR", "NL"],
    ["HARTFIELD", "NB"],
    ["HARTFORD", "NB"],
    ["HARTIN SETTLEMENT", "NB"],
    ["HARTINGTON", "ON"],
    ["HARTLAND", "NB"],
    ["HARTLEY BAY", "BC"],
    ["HARTLEY SETTLEMENT", "NB"],
    ["HARTNEY", "MB"],
    ["HARTY", "ON"],
    ["HARVEY ALBERT CO", "NB"],
    ["HARVEY STATION", "NB"],
    ["HARVEY YORK CO", "NB"],
    ["HARVIE HEIGHTS", "AB"],
    ["HARWOOD", "ON"],
    ["HASTINGS", "ON"],
    ["HATCHET LAKE", "NS"],
    ["HATFIELD POINT", "NB"],
    ["HATLEY", "QC"],
    ["HAUT-LAMEQUE", "NB"],
    ["HAUT-PAQUETVILLE", "NB"],
    ["HAUT-RIVIERE-DU-PORTAGE", "NB"],
    ["HAUT-SAINT-ANTOINE", "NB"],
    ["HAUT-SHEILA", "NB"],
    ["HAUT-SHIPPAGAN", "NB"],
    ["HAUTE-ABOUJAGANE", "NB"],
    ["HAVELOCK", "NB"],
    ["HAVELOCK", "ON"],
    ["HAVELOCK", "QC"],
    ["HAVRE BOUCHER", "NS"],
    ["HAVRE-AUBERT", "QC"],
    ["HAVRE-AUX-MAISONS", "QC"],
    ["HAVRE-SAINT-PIERRE", "QC"],
    ["HAWARDEN", "SK"],
    ["HAWK JUNCTION", "ON"],
    ["HAWKES BAY", "NL"],
    ["HAWKESBURY", "ON"],
    ["HAWKESTONE", "ON"],
    ["HAWKESVILLE", "ON"],
    ["HAWKINS CORNER", "NB"],
    ["HAWKSHAW", "NB"],
    ["HAY LAKES", "AB"],
    ["HAY RIVER", "NT"],
    ["HAY SETTLEMENT", "NB"],
    ["HAY", "ON"],
    ["HAYDON", "ON"],
    ["HAYESVILLE", "NB"],
    ["HAYMAN HILL", "NB"],
    ["HAYS", "AB"],
    ["HAYTER", "AB"],
    ["HAYWOOD", "MB"],
    ["HAZEL DELL", "SK"],
    ["HAZELDEAN", "NB"],
    ["HAZELRIDGE", "MB"],
    ["HAZELTON", "BC"],
    ["HAZELTON", "NB"],
    ["HAZENMORE", "SK"],
    ["HAZLET", "SK"],
    ["HEAD BAY D'ESPOIR", "NL"],
    ["HEAD OF CHEZZETCOOK", "NS"],
    ["HEAD OF JEDDORE", "NS"],
    ["HEAD OF MILLSTREAM", "NB"],
    ["HEAD OF ST MARGARETS BAY", "NS"],
    ["HEADINGLEY", "MB"],
    ["HEARNE", "SK"],
    ["HEARST", "ON"],
    ["HEART'S CONTENT", "NL"],
    ["HEART'S DELIGHT", "NL"],
    ["HEART'S DESIRE", "NL"],
    ["HEATHCOTE", "ON"],
    ["HEATHERTON", "NL"],
    ["HEATHERTON", "NS"],
    ["HEATHLAND", "NB"],
    ["HEBBS CROSS", "NS"],
    ["HEBBVILLE", "NS"],
    ["HEBERT", "NB"],
    ["HEBERTVILLE", "QC"],
    ["HEBERTVILLE-STATION", "QC"],
    ["HEBRON", "NB"],
    ["HEBRON", "NS"],
    ["HEDLEY", "BC"],
    ["HEFFLEY CREEK", "BC"],
    ["HEIDELBERG", "ON"],
    ["HEINSBURG", "AB"],
    ["HEISLER", "AB"],
    ["HEMMINGFORD", "QC"],
    ["HENDERSON SETTLEMENT", "NB"],
    ["HENDON", "SK"],
    ["HENRIBOURG", "SK"],
    ["HENRYVILLE", "QC"],
    ["HENSALL", "ON"],
    ["HEPBURN", "SK"],
    ["HEPWORTH", "ON"],
    ["HERBERT", "SK"],
    ["HERIOT BAY", "BC"],
    ["HERMITAGE", "NL"],
    ["HERON BAY", "ON"],
    ["HEROUXVILLE", "QC"],
    ["HERRING COVE", "NS"],
    ["HERRING NECK", "NL"],
    ["HERSCHEL", "SK"],
    ["HERSONVILLE", "NB"],
    ["HEWARD", "SK"],
    ["HIBERNIA COVE", "NB"],
    ["HICKMANS HARBOUR", "NL"],
    ["HICKSON", "ON"],
    ["HICKSVILLE", "NB"],
    ["HIGH BLUFF", "MB"],
    ["HIGH LEVEL", "AB"],
    ["HIGH PRAIRIE", "AB"],
    ["HIGH RIVER", "AB"],
    ["HIGHFIELD", "NB"],
    ["HIGHGATE", "ON"],
    ["HIGHLAND GROVE", "ON"],
    ["HIGHLAND HILL", "NS"],
    ["HIGHLANDS", "NL"],
    ["HILBRE", "MB"],
    ["HILDA", "AB"],
    ["HILL SPRING", "AB"],
    ["HILLANDALE", "NB"],
    ["HILLCREST MINES", "AB"],
    ["HILLGRADE", "NL"],
    ["HILLGROVE", "NB"],
    ["HILLIARD", "AB"],
    ["HILLIARDTON", "ON"],
    ["HILLIER", "ON"],
    ["HILLSBOROUGH WEST", "NB"],
    ["HILLSBOROUGH", "NB"],
    ["HILLSBURGH", "ON"],
    ["HILLSDALE", "NB"],
    ["HILLSDALE", "ON"],
    ["HILLSIDE BOULARDERIE", "NS"],
    ["HILLTOP", "NB"],
    ["HILLVIEW", "NL"],
    ["HILTON BEACH", "ON"],
    ["HINCHINBROOKE", "QC"],
    ["HINES CREEK", "AB"],
    ["HINTON", "AB"],
    ["HIXON", "BC"],
    ["HOBBEMA", "AB"],
    ["HODGES COVE", "NL"],
    ["HODGEVILLE", "SK"],
    ["HODGSON", "MB"],
    ["HOEY", "SK"],
    ["HOLBEIN", "SK"],
    ["HOLBERG", "BC"],
    ["HOLDEN", "AB"],
    ["HOLDFAST", "SK"],
    ["HOLLAND CENTRE", "ON"],
    ["HOLLAND LANDING", "ON"],
    ["HOLLAND", "MB"],
    ["HOLMESVILLE", "NB"],
    ["HOLMFIELD", "MB"],
    ["HOLSTEIN", "ON"],
    ["HOLTVILLE", "NB"],
    ["HOLTYRE", "ON"],
    ["HOLYROOD", "NL"],
    ["HOLYROOD", "ON"],
    ["HOMEVILLE", "NS"],
    ["HOMEWOOD", "MB"],
    ["HONDO", "AB"],
    ["HONEY HARBOUR", "ON"],
    ["HONEYDALE", "NB"],
    ["HONEYMOON BAY", "BC"],
    ["HONEYWOOD", "ON"],
    ["HONFLEUR", "QC"],
    ["HOOSIER", "SK"],
    ["HOPE", "BC"],
    ["HOPE", "QC"],
    ["HOPEALL", "NL"],
    ["HOPEDALE", "NL"],
    ["HOPEWELL CAPE", "NB"],
    ["HOPEWELL HILL", "NB"],
    ["HOPEWELL", "NS"],
    ["HORNBY ISLAND", "BC"],
    ["HORNBY", "ON"],
    ["HORNDEAN", "MB"],
    ["HORNELL HEIGHTS", "ON"],
    ["HORNEPAYNE", "ON"],
    ["HORNINGS MILLS", "ON"],
    ["HORSEFLY", "BC"],
    ["HORWOOD", "NL"],
    ["HOTCHKISS", "AB"],
    ["HOUSTON", "BC"],
    ["HOWARD BROOK", "NB"],
    ["HOWARD", "NB"],
    ["HOWDEN", "MB"],
    ["HOWICK", "QC"],
    ["HOWIE CENTER", "NS"],
    ["HOWLAND RIDGE", "NB"],
    ["HOWLEY", "NL"],
    ["HOYT", "NB"],
    ["HUBBARD", "SK"],
    ["HUBBARDS", "NS"],
    ["HUBERDEAU", "QC"],
    ["HUBLEY", "NS"],
    ["HUDSON BAY", "SK"],
    ["HUDSON HEIGHTS", "QC"],
    ["HUDSON", "ON"],
    ["HUDSON", "QC"],
    ["HUDSON'S HOPE", "BC"],
    ["HUGHENDEN", "AB"],
    ["HUMBOLDT", "SK"],
    ["HUNTA", "ON"],
    ["HUNTERS HOME", "NB"],
    ["HUNTINGDON", "QC"],
    ["HUNTINGTON", "NS"],
    ["HUNTS POINT", "NS"],
    ["HUNTSVILLE", "ON"],
    ["HURON PARK", "ON"],
    ["HUSSAR", "AB"],
    ["HUXLEY", "AB"],
    ["HYAS", "SK"],
    ["HYLO", "AB"],
    ["HYTHE", "AB"],
    ["IDDESLEIGH", "AB"],
    ["IGLOOLIK", "NU"],
    ["IGNACE", "ON"],
    ["ILDERTON", "ON"],
    ["ILE DES CHENES", "MB"],
    ["ILE DU GRAND-CALUMET", "QC"],
    ["ILE-A-LA-CROSSE", "SK"],
    ["ILE-AUX-NOIX", "QC"],
    ["ILFORD", "MB"],
    ["IMMIGRANT ROAD", "NB"],
    ["IMPERIAL", "SK"],
    ["INDIAN BAY BB", "NL"],
    ["INDIAN BROOK 14", "NS"],
    ["INDIAN HARBOUR", "NS"],
    ["INDIAN HEAD", "SK"],
    ["INDIAN ISLAND", "NB"],
    ["INDIAN MOUNTAIN", "NB"],
    ["INDIAN PATH", "NS"],
    ["INDIAN RIVER", "ON"],
    ["INDUS", "AB"],
    ["INGERSOLL", "ON"],
    ["INGLESIDE", "ON"],
    ["INGLEWOOD", "ON"],
    ["INGLIS", "MB"],
    ["INGOLF", "ON"],
    ["INGOMAR", "NS"],
    ["INGONISH BEACH", "NS"],
    ["INGONISH", "NS"],
    ["INGRAMPORT", "NS"],
    ["INKERMAN FERRY", "NB"],
    ["INKERMAN", "NB"],
    ["INKERMAN", "ON"],
    ["INNERKIP", "ON"],
    ["INNISFAIL", "AB"],
    ["INNISFIL", "ON"],
    ["INNISFREE", "AB"],
    ["INSINGER", "SK"],
    ["INTERVALE", "NB"],
    ["INUKJUAK", "QC"],
    ["INUVIK", "NT"],
    ["INVERARY", "ON"],
    ["INVERMAY", "SK"],
    ["INVERMERE", "BC"],
    ["INVERNESS", "NS"],
    ["INVERNESS", "QC"],
    ["INWOOD", "MB"],
    ["INWOOD", "ON"],
    ["IONA STATION", "ON"],
    ["IONA", "NS"],
    ["IQALUIT", "NU"],
    ["IRISH COVE", "NS"],
    ["IRISH SETTLEMENT", "NB"],
    ["IRISHTOWN", "NB"],
    ["IRISHVALE", "NS"],
    ["IRLANDE", "QC"],
    ["IRMA", "AB"],
    ["IRON BOUND COVE", "NB"],
    ["IRON BRIDGE", "ON"],
    ["IRON RIVER", "AB"],
    ["IRON SPRINGS", "AB"],
    ["IRONDALE", "ON"],
    ["IRONVILLE", "NS"],
    ["IROQUOIS FALLS A", "ON"],
    ["IROQUOIS FALLS", "ON"],
    ["IROQUOIS", "ON"],
    ["IRRICANA", "AB"],
    ["IRVINE", "AB"],
    ["ISAACS HARBOUR", "NS"],
    ["ISABELLA", "MB"],
    ["ISKUT", "BC"],
    ["ISLAND HARBOUR", "NL"],
    ["ISLAND LAKE SOUTH", "AB"],
    ["ISLAND LAKE", "AB"],
    ["ISLAND LAKE", "MB"],
    ["ISLAND LAKE", "SK"],
    ["ISLAND VIEW", "NB"],
    ["ISLANDVIEW", "NS"],
    ["ISLAY", "AB"],
    ["ISLE-AUX-COUDRES", "QC"],
    ["ISLE-AUX-MORTS", "NL"],
    ["ISLINGTON", "NL"],
    ["ISSOUDUN", "QC"],
    ["ITALY CROSS", "NS"],
    ["ITUNA", "SK"],
    ["IVRY-SUR-LE-LAC", "QC"],
    ["IVUJIVIK", "QC"],
    ["JACKFISH LAKE", "SK"],
    ["JACKSON FALLS", "NB"],
    ["JACKSONS ARM", "NL"],
    ["JACKSONS COVE", "NL"],
    ["JACKSONS POINT", "ON"],
    ["JACKSONTOWN", "NB"],
    ["JACKSONVILLE", "NB"],
    ["JACQUES-CARTIER", "QC"],
    ["JADE CITY", "BC"],
    ["JAFFRAY", "BC"],
    ["JAMES RIVER BRIDGE", "AB"],
    ["JAMESVILLE", "NS"],
    ["JANETVILLE", "ON"],
    ["JANEVILLE", "NB"],
    ["JANSEN", "SK"],
    ["JARDINEVILLE", "NB"],
    ["JARVIE", "AB"],
    ["JARVIS BAY", "AB"],
    ["JARVIS", "ON"],
    ["JASPER", "AB"],
    ["JASPER", "ON"],
    ["JEAN COTE", "AB"],
    ["JEDBURGH", "SK"],
    ["JEDDORE OYSTER PONDS", "NS"],
    ["JEFFREYS", "NL"],
    ["JEFFRIES CORNER", "NB"],
    ["JELLICOE", "ON"],
    ["JEMSEG", "NB"],
    ["JENNER", "AB"],
    ["JERSEYSIDE", "NL"],
    ["JERSEYVILLE", "ON"],
    ["JEWETTS MILLS", "NB"],
    ["JOBS COVE", "NL"],
    ["JOE BATTS ARM", "NL"],
    ["JOGGINS", "NS"],
    ["JOGUES", "ON"],
    ["JOHN D'OR PRAIRIE", "AB"],
    ["JOHNSON SETTLEMENT CHARLOTTE C", "NB"],
    ["JOHNSON SETTLEMENT YORK CO", "NB"],
    ["JOHNSON'S MILLS", "NB"],
    ["JOHNSTON POINT", "NB"],
    ["JOHNVILLE", "NB"],
    ["JOLICURE", "NB"],
    ["JOLIETTE", "QC"],
    ["JOLY", "QC"],
    ["JONQUIERE", "QC"],
    ["JORDAN FALLS", "NS"],
    ["JORDAN MOUNTAIN", "NB"],
    ["JORDAN RIVER", "BC"],
    ["JORDAN STATION", "ON"],
    ["JOUSSARD", "AB"],
    ["JOYCEVILLE", "ON"],
    ["JUDIQUE", "NS"],
    ["JUNIPER ISLAND", "ON"],
    ["JUNIPER MOUNTAIN", "NS"],
    ["JUNIPER", "NB"],
    ["JUSKATLA", "BC"],
    ["JUSTICE", "MB"],
    ["KAGAWONG", "ON"],
    ["KAHNAWAKE", "QC"],
    ["KAKABEKA FALLS", "ON"],
    ["KALADAR", "ON"],
    ["KALEDEN", "BC"],
    ["KAMINISTIQUIA", "ON"],
    ["KAMLOOPS", "BC"],
    ["KAMOURASKA", "QC"],
    ["KAMSACK", "SK"],
    ["KANANASKIS", "AB"],
    ["KANATA", "ON"],
    ["KANGIQSUALUJJUAQ", "QC"],
    ["KANGIQSUJUAQ", "QC"],
    ["KANGIRSUK", "QC"],
    ["KAPASIWIN", "AB"],
    ["KAPUSKASING", "ON"],
    ["KARS", "NB"],
    ["KARS", "ON"],
    ["KASABONIKA", "ON"],
    ["KASHABOWIE", "ON"],
    ["KASHECHEWAN", "ON"],
    ["KASLO", "BC"],
    ["KATHYRN", "AB"],
    ["KATRINE", "ON"],
    ["KAWAWACHIKAMACH", "QC"],
    ["KAYVILLE", "SK"],
    ["KAZABAZUA", "QC"],
    ["KEARNEY", "ON"],
    ["KEARNS", "ON"],
    ["KEDGWICK NORD", "NB"],
    ["KEDGWICK OUEST", "NB"],
    ["KEDGWICK RIVER", "NB"],
    ["KEDGWICK SUD", "NB"],
    ["KEDGWICK", "NB"],
    ["KEELER", "SK"],
    ["KEELS", "NL"],
    ["KEENANS", "NB"],
    ["KEENE", "ON"],
    ["KEEWATIN", "ON"],
    ["KEEWAYWIN", "ON"],
    ["KEG RIVER", "AB"],
    ["KEGASKA", "QC"],
    ["KEHEWIN", "AB"],
    ["KEJICK", "ON"],
    ["KELFIELD", "SK"],
    ["KELLIHER", "SK"],
    ["KELOWNA", "BC"],
    ["KELSEY", "AB"],
    ["KELVINGTON", "SK"],
    ["KELWOOD", "MB"],
    ["KEMBLE", "ON"],
    ["KEMPT HEAD", "NS"],
    ["KEMPTOWN", "NS"],
    ["KEMPTVILLE", "NS"],
    ["KEMPTVILLE", "ON"],
    ["KENABEEK", "ON"],
    ["KENASTON", "SK"],
    ["KENDAL", "ON"],
    ["KENDAL", "SK"],
    ["KENILWORTH", "ON"],
    ["KENMORE", "ON"],
    ["KENNEDY", "SK"],
    ["KENNETCOOK", "NS"],
    ["KENORA", "ON"],
    ["KENOSEE LAKE", "SK"],
    ["KENSINGTON", "PE"],
    ["KENT BRIDGE", "ON"],
    ["KENT JUNCTION", "NB"],
    ["KENTON", "MB"],
    ["KENTVILLE", "NS"],
    ["KENVILLE", "MB"],
    ["KEOMA", "AB"],
    ["KEREMEOS", "BC"],
    ["KERROBERT", "SK"],
    ["KERWOOD", "ON"],
    ["KESWICK RIDGE", "NB"],
    ["KESWICK", "NB"],
    ["KESWICK", "ON"],
    ["KETCH HARBOUR", "NS"],
    ["KETTLEBY", "ON"],
    ["KHEDIVE", "SK"],
    ["KIAMIKA", "QC"],
    ["KIERSTEAD MOUNTAIN", "NB"],
    ["KIERSTEADVILLE", "NB"],
    ["KIKINO", "AB"],
    ["KILBRIDE", "NL"],
    ["KILBURN", "NB"],
    ["KILDONAN", "BC"],
    ["KILLALOE", "ON"],
    ["KILLALY", "SK"],
    ["KILLAM", "AB"],
    ["KILLAMS MILLS", "NB"],
    ["KILLARNEY ROAD", "NB"],
    ["KILLARNEY", "MB"],
    ["KILLARNEY", "ON"],
    ["KILLOWEEN", "NB"],
    ["KILWORTHY", "ON"],
    ["KIMBERLEY", "BC"],
    ["KIMBERLEY", "ON"],
    ["KIMMIRUT", "NU"],
    ["KINBURN", "ON"],
    ["KINCAID", "SK"],
    ["KINCARDINE", "NB"],
    ["KINCARDINE", "ON"],
    ["KINCOLITH", "BC"],
    ["KINDERSLEY", "SK"],
    ["KING CITY", "ON"],
    ["KING KIRKLAND", "ON"],
    ["KINGCOME INLET", "BC"],
    ["KINGFISHER LAKE", "ON"],
    ["KINGMAN", "AB"],
    ["KINGS COVE", "NL"],
    ["KINGS LANDING HISTORICAL SETTL", "NB"],
    ["KINGS POINT", "NL"],
    ["KINGSBURY", "QC"],
    ["KINGSCLEAR FIRST NATION", "NB"],
    ["KINGSEY FALLS", "QC"],
    ["KINGSGATE", "BC"],
    ["KINGSLEY", "NB"],
    ["KINGSTON", "NB"],
    ["KINGSTON", "NS"],
    ["KINGSTON", "ON"],
    ["KINGSVILLE", "ON"],
    ["KINISTINO", "SK"],
    ["KINKORA", "PE"],
    ["KINLEY", "SK"],
    ["KINMOUNT", "ON"],
    ["KINNEAR SETTLEMENT", "NB"],
    ["KINNEAR'S MILLS", "QC"],
    ["KINOOSAO", "SK"],
    ["KINOSOTA", "MB"],
    ["KINSAC", "NS"],
    ["KINSELLA", "AB"],
    ["KINTORE", "ON"],
    ["KINUSO", "AB"],
    ["KIPAWA", "QC"],
    ["KIPLING", "SK"],
    ["KIPPEN", "ON"],
    ["KIPPENS", "NL"],
    ["KIRKELLA", "MB"],
    ["KIRKFIELD", "ON"],
    ["KIRKLAND LAKE", "ON"],
    ["KIRKLAND", "NB"],
    ["KIRKLAND", "QC"],
    ["KIRKTON", "ON"],
    ["KIRRIEMUIR", "AB"],
    ["KISBEY", "SK"],
    ["KITCHENER", "BC"],
    ["KITCHENER", "ON"],
    ["KITIMAT", "BC"],
    ["KITKATLA", "BC"],
    ["KITSCOTY", "AB"],
    ["KITWANGA", "BC"],
    ["KLEEFELD", "MB"],
    ["KLEENA KLEENE", "BC"],
    ["KLEINBURG", "ON"],
    ["KLEMTU", "BC"],
    ["KNIGHTS COVE", "NL"],
    ["KNIGHTVILLE", "NB"],
    ["KNOWLESVILLE", "NB"],
    ["KNOWLTON", "QC"],
    ["KNUTSFORD", "BC"],
    ["KOKSILAH", "BC"],
    ["KOLA", "MB"],
    ["KOMARNO", "MB"],
    ["KOMOKA", "ON"],
    ["KOOSTATAK", "MB"],
    ["KOOTENAY BAY", "BC"],
    ["KOUCHIBOUGUAC NATIONAL PARK", "NB"],
    ["KOUCHIBOUGUAC", "NB"],
    ["KRONAU", "SK"],
    ["KRYDOR", "SK"],
    ["KUGAARUK", "NU"],
    ["KUGLUKTUK", "NU"],
    ["KUROKI", "SK"],
    ["KUUJJUAQ", "QC"],
    ["KUUJJUARAPIK", "QC"],
    ["KYLE", "SK"],
    ["KYLEMORE", "SK"],
    ["KYUQUOT", "BC"],
    ["L'ALVERNE", "QC"],
    ["L'AMABLE", "ON"],
    ["L'ANCIENNE-LORETTE", "QC"],
    ["L'ANGE GARDIEN", "QC"],
    ["L'ANGE-GARDIEN", "QC"],
    ["L'ANSE AU CLAIR", "NL"],
    ["L'ANSE AU LOUP", "NL"],
    ["L'ANSE-PLEUREUSE", "QC"],
    ["L'ANSE-SAINT-JEAN", "QC"],
    ["L'ARDOISE", "NS"],
    ["L'ASCENSION", "QC"],
    ["L'ASCENSION-DE-NOTRE-SEIGNEUR", "QC"],
    ["L'ASCENSION-DE-PATAPEDIA", "QC"],
    ["L'ASSOMPTION", "QC"],
    ["L'AVENIR", "QC"],
    ["L'EPIPHANIE", "QC"],
    ["L'ETANG-DU-NORD", "QC"],
    ["L'ETETE", "NB"],
    ["L'ILE-BIZARD", "QC"],
    ["L'ILE-CADIEUX", "QC"],
    ["L'ILE-D'ENTREE", "QC"],
    ["L'ILE-MICHON", "QC"],
    ["L'ILE-PERROT", "QC"],
    ["L'ISLE-AUX-GRUES", "QC"],
    ["L'ISLE-VERTE", "QC"],
    ["L'ISLET", "QC"],
    ["L'ISLETVILLE", "QC"],
    ["L'ORIGNAL", "ON"],
    ["LA BAIE", "QC"],
    ["LA BALEINE", "QC"],
    ["LA BARRIERE", "MB"],
    ["LA BOSTONNAIS", "QC"],
    ["LA BROQUERIE", "MB"],
    ["LA CONCEPTION", "QC"],
    ["LA COREY", "AB"],
    ["LA CORNE", "QC"],
    ["LA CRETE", "AB"],
    ["LA CROCHE", "QC"],
    ["LA DORE", "QC"],
    ["LA DURANTAYE", "QC"],
    ["LA GLACE", "AB"],
    ["LA GUADELOUPE", "QC"],
    ["LA HAVE", "NS"],
    ["LA LOCHE", "SK"],
    ["LA MACAZA", "QC"],
    ["LA MALBAIE", "QC"],
    ["LA MARTRE", "QC"],
    ["LA MINERVE", "QC"],
    ["LA MORANDIERE", "QC"],
    ["LA MOTTE", "QC"],
    ["LA PATRIE", "QC"],
    ["LA POCATIERE", "QC"],
    ["LA POILE", "NL"],
    ["LA PRAIRIE", "QC"],
    ["LA PRESENTATION", "QC"],
    ["LA REDEMPTION", "QC"],
    ["LA REINE", "QC"],
    ["LA RIVIERE", "MB"],
    ["LA RONGE", "SK"],
    ["LA SALETTE", "ON"],
    ["LA SALLE", "MB"],
    ["LA SARRE", "QC"],
    ["LA SCIE", "NL"],
    ["LA TABATIERE", "QC"],
    ["LA TRINITE-DES-MONTS", "QC"],
    ["LA TUQUE", "QC"],
    ["LA VISITATION-DE-L'ILE-DUPAS", "QC"],
    ["LA VISITATION-DE-YAMASKA", "QC"],
    ["LABELLE", "NS"],
    ["LABELLE", "QC"],
    ["LABRADOR CITY", "NL"],
    ["LABRECQUE", "QC"],
    ["LAC BAKER", "NB"],
    ["LAC BROCHET", "MB"],
    ["LAC DES ARCS", "AB"],
    ["LAC DES LOUPS", "QC"],
    ["LAC DU BONNET", "MB"],
    ["LAC LA BICHE", "AB"],
    ["LAC LA HACHE", "BC"],
    ["LAC SEUL", "ON"],
    ["LAC VERT", "SK"],
    ["LAC-A-LA-TORTUE", "QC"],
    ["LAC-AU-SAUMON", "QC"],
    ["LAC-AUX-SABLES", "QC"],
    ["LAC-BEAUPORT", "QC"],
    ["LAC-BOUCHETTE", "QC"],
    ["LAC-CAYAMANT", "QC"],
    ["LAC-DELAGE", "QC"],
    ["LAC-DES-AIGLES", "QC"],
    ["LAC-DES-ECORCES", "QC"],
    ["LAC-DES-ILES", "QC"],
    ["LAC-DES-PLAGES", "QC"],
    ["LAC-DES-SEIZE-ILES", "QC"],
    ["LAC-DROLET", "QC"],
    ["LAC-DU-CERF", "QC"],
    ["LAC-EDOUARD", "QC"],
    ["LAC-ETCHEMIN", "QC"],
    ["LAC-FRONTIERE", "QC"],
    ["LAC-HUMQUI", "QC"],
    ["LAC-KENOGAMI", "QC"],
    ["LAC-MEGANTIC", "QC"],
    ["LAC-SAGUAY", "QC"],
    ["LAC-SAINT-JOSEPH", "QC"],
    ["LAC-SAINT-PAUL", "QC"],
    ["LAC-SAINTE-MARIE", "QC"],
    ["LAC-SERGENT", "QC"],
    ["LAC-SIMON", "QC"],
    ["LAC-SUPERIEUR", "QC"],
    ["LACADENA", "SK"],
    ["LACHINE", "QC"],
    ["LACHUTE", "QC"],
    ["LACOLLE", "QC"],
    ["LACOMBE COUNTY", "AB"],
    ["LACOMBE", "AB"],
    ["LACONIA", "NS"],
    ["LADLE COVE", "NL"],
    ["LADRIERE", "QC"],
    ["LADYSMITH", "BC"],
    ["LADYSMITH", "QC"],
    ["LAFLECHE", "SK"],
    ["LAFOND", "AB"],
    ["LAFORCE", "QC"],
    ["LAGACEVILLE", "NB"],
    ["LAIRD", "SK"],
    ["LAJORD", "SK"],
    ["LAKE ALMA", "SK"],
    ["LAKE AUDY", "MB"],
    ["LAKE CHARLOTTE", "NS"],
    ["LAKE COWICHAN", "BC"],
    ["LAKE ECHO", "NS"],
    ["LAKE EDWARD", "NB"],
    ["LAKE EGMONT", "NS"],
    ["LAKE ERROCK", "BC"],
    ["LAKE FRANCIS", "MB"],
    ["LAKE GEORGE", "NB"],
    ["LAKE ISLE", "AB"],
    ["LAKE LENORE", "SK"],
    ["LAKE LOUISE", "AB"],
    ["LAKE MANITOBA FIRST NATION", "MB"],
    ["LAKE OF BAYS", "ON"],
    ["LAKE ST PETER", "ON"],
    ["LAKE UIST", "NS"],
    ["LAKEFIELD", "ON"],
    ["LAKEHURST", "ON"],
    ["LAKELAND", "MB"],
    ["LAKESIDE", "NB"],
    ["LAKESIDE", "NS"],
    ["LAKESIDE", "ON"],
    ["LAKETON", "NB"],
    ["LAKEVIEW", "NS"],
    ["LAKEVILLE CARLETON CO", "NB"],
    ["LAKEVILLE CORNER", "NB"],
    ["LAKEVILLE-WESTMORLAND", "NB"],
    ["LAMALINE", "NL"],
    ["LAMARCHE", "QC"],
    ["LAMARTINE", "QC"],
    ["LAMBERT'S COVE", "NB"],
    ["LAMBERTVILLE", "NB"],
    ["LAMBTON", "QC"],
    ["LAMEQUE", "NB"],
    ["LAMONT", "AB"],
    ["LAMPMAN", "SK"],
    ["LANARK", "ON"],
    ["LANCASTER PARK", "AB"],
    ["LANCASTER", "ON"],
    ["LANCE COVE", "NL"],
    ["LANCER", "SK"],
    ["LANDIS", "SK"],
    ["LANDMARK", "MB"],
    ["LANDRIENNE", "QC"],
    ["LANDRY OFFICE", "NB"],
    ["LANESVILLE", "NS"],
    ["LANG", "SK"],
    ["LANGBANK", "SK"],
    ["LANGDON", "AB"],
    ["LANGENBURG", "SK"],
    ["LANGHAM", "SK"],
    ["LANGLEY", "BC"],
    ["LANGRUTH", "MB"],
    ["LANGTON", "ON"],
    ["LANIEL", "QC"],
    ["LANIGAN", "SK"],
    ["LANORAIE", "QC"],
    ["LANSDOWNE HOUSE", "ON"],
    ["LANSDOWNE", "NB"],
    ["LANSDOWNE", "ON"],
    ["LANTIER", "QC"],
    ["LANTZ", "NS"],
    ["LANTZVILLE", "BC"],
    ["LAPLAND", "NS"],
    ["LAPLANTE", "NB"],
    ["LAPORTE", "SK"],
    ["LARDER LAKE", "ON"],
    ["LARK HARBOUR", "NL"],
    ["LAROUCHE", "QC"],
    ["LARRYS RIVER", "NS"],
    ["LASALLE", "ON"],
    ["LASALLE", "QC"],
    ["LASHBURN", "SK"],
    ["LASQUETI", "BC"],
    ["LATCHFORD", "ON"],
    ["LATERRIERE", "QC"],
    ["LATULIPE", "QC"],
    ["LAUDER", "MB"],
    ["LAUNAY", "QC"],
    ["LAUREL", "ON"],
    ["LAURENCETON", "NL"],
    ["LAURIER", "MB"],
    ["LAURIER-STATION", "QC"],
    ["LAURIERVILLE", "QC"],
    ["LAVAL", "QC"],
    ["LAVAL-OUEST", "QC"],
    ["LAVALTRIE", "QC"],
    ["LAVENHAM", "MB"],
    ["LAVERLOCHERE", "QC"],
    ["LAVIGNE", "ON"],
    ["LAVILLETTE", "NB"],
    ["LAVINGTON", "BC"],
    ["LAVOY", "AB"],
    ["LAWN", "NL"],
    ["LAWRENCE STATION", "NB"],
    ["LAWRENCETOWN", "NS"],
    ["LAWRENCETOWN.", "NS"],
    ["LAWRENCEVILLE", "QC"],
    ["LAX KW'ALAAMS", "BC"],
    ["LAZO", "BC"],
    ["LE BIC", "QC"],
    ["LE GARDEUR", "QC"],
    ["LE GOULET", "NB"],
    ["LEADER", "SK"],
    ["LEADING TICKLES", "NL"],
    ["LEAF RAPIDS", "MB"],
    ["LEAMINGTON", "ON"],
    ["LEASK", "SK"],
    ["LEASKDALE", "ON"],
    ["LEBEL-SUR-QUEVILLON", "QC"],
    ["LEBRET", "SK"],
    ["LECLERCVILLE", "QC"],
    ["LEDUC COUNTY", "AB"],
    ["LEDUC", "AB"],
    ["LEE SETTLEMENT", "NB"],
    ["LEECH", "NB"],
    ["LEFAIVRE", "ON"],
    ["LEFEBVRE", "QC"],
    ["LEFROY", "ON"],
    ["LEGAL", "AB"],
    ["LEITCHES CREEK", "NS"],
    ["LEITH", "ON"],
    ["LEJEUNE", "QC"],
    ["LEMBERG", "SK"],
    ["LEMIEUX", "QC"],
    ["LEMOYNE", "QC"],
    ["LENNOX ISLAND", "PE"],
    ["LENORE", "MB"],
    ["LEONARD COLONY", "NB"],
    ["LEONARDVILLE", "NB"],
    ["LEOVILLE", "SK"],
    ["LEPREAU", "NB"],
    ["LEROSS", "SK"],
    ["LEROY", "SK"],
    ["LERY", "QC"],
    ["LES BUISSONS", "QC"],
    ["LES CEDRES", "QC"],
    ["LES COTEAUX", "QC"],
    ["LES EBOULEMENTS", "QC"],
    ["LES ESCOUMINS", "QC"],
    ["LES HAUTEURS", "QC"],
    ["LES MECHINS", "QC"],
    ["LESLIE", "SK"],
    ["LESLIEVILLE", "AB"],
    ["LESTOCK", "SK"],
    ["LETANG", "NB"],
    ["LETELLIER", "MB"],
    ["LETHBRIDGE", "AB"],
    ["LETHBRIDGE", "NL"],
    ["LEVACK", "ON"],
    ["LEVERVILLE", "NB"],
    ["LEVIS", "QC"],
    ["LEWINS COVE", "NL"],
    ["LEWIS LAKE", "NS"],
    ["LEWIS MOUNTAIN", "NB"],
    ["LEWISPORTE", "NL"],
    ["LEWVAN", "SK"],
    ["LEXINGTON", "NS"],
    ["LIBAU", "MB"],
    ["LIBERTY", "SK"],
    ["LIEBENTHAL", "SK"],
    ["LIKELY", "BC"],
    ["LILLOOET", "BC"],
    ["LIMEHOUSE", "ON"],
    ["LIMEKILN", "NB"],
    ["LIMERICK", "SK"],
    ["LIMESTONE", "NB"],
    ["LIMOGES", "ON"],
    ["LINCOLN", "NB"],
    ["LINDALE", "AB"],
    ["LINDBERGH", "AB"],
    ["LINDELL BEACH", "BC"],
    ["LINDEN", "AB"],
    ["LINDSAY", "NB"],
    ["LINDSAY", "ON"],
    ["LINGAN ROAD", "NS"],
    ["LINGAN", "NS"],
    ["LINGWICK", "QC"],
    ["LINTLAW", "SK"],
    ["LINTON CORNER", "NB"],
    ["LINWOOD", "ON"],
    ["LIONS BAY", "BC"],
    ["LIONS HEAD", "ON"],
    ["LIPTON", "SK"],
    ["LISCOMB", "NS"],
    ["LISIEUX", "SK"],
    ["LISLE", "ON"],
    ["LISTER", "BC"],
    ["LISTOWEL", "ON"],
    ["LISTUGUJ", "QC"],
    ["LITTLE BARTIBOG", "NB"],
    ["LITTLE BAY EAST", "NL"],
    ["LITTLE BAY ISLANDS", "NL"],
    ["LITTLE BAY NDB", "NL"],
    ["LITTLE BAY PB", "NL"],
    ["LITTLE BRAS D'OR", "NS"],
    ["LITTLE BRITAIN", "ON"],
    ["LITTLE BROOK", "NS"],
    ["LITTLE BULLHEAD", "MB"],
    ["LITTLE BURNT BAY", "NL"],
    ["LITTLE CATALINA", "NL"],
    ["LITTLE CURRENT", "ON"],
];
